name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: golang:1.20  # Using the official Go Docker image
    steps:
    - uses: actions/checkout@v4

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
