name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'
    - name: Build and package
      run: |
        go build -v -buildvcs=false ./...
        go test -v -buildvcs=false ./...
    - name: Create release
      uses: actions/create-release@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        release_name: ${{ github.event.release.name }}
        release_body: ${{ github.event.release.body }}
        draft: false
        prerelease: false
    - name: Update version
      run: |
        echo "Updating version..."
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git checkout main
        git pull origin main
        version=$(git describe --tags --abbrev=0)
        new_version=$(echo "$version" | awk -F. '{print $1 "." $2 "." $3 + 1}')
        echo "New version: $new_version"
        git tag -a "v$new_version" -m "Release $new_version"
        git push origin "v$new_version"
        git push origin main
